// Code generated by "stringer -type=PatternGrade"; DO NOT EDIT.

package easypoker

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoGrade-0]
	_ = x[HighCard-1]
	_ = x[Pair-2]
	_ = x[TwoPair-3]
	_ = x[ThreeOfAKind-4]
	_ = x[Straight-5]
	_ = x[Flush-6]
	_ = x[FullHouse-7]
	_ = x[FourOfAKind-8]
	_ = x[StraightFlush-9]
	_ = x[RoyalFlush-10]
}

const _PatternGrade_name = "NoGradeHighCardPairTwoPairThreeOfAKindStraightFlushFullHouseFourOfAKindStraightFlushRoyalFlush"

var _PatternGrade_index = [...]uint8{0, 7, 15, 19, 26, 38, 46, 51, 60, 71, 84, 94}

func (i PatternGrade) String() string {
	if i >= PatternGrade(len(_PatternGrade_index)-1) {
		return "PatternGrade(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PatternGrade_name[_PatternGrade_index[i]:_PatternGrade_index[i+1]]
}
